### PR TITLE
Remove xerrors dependency and use stdlib.

### PR DESCRIPTION
**Pull request by googollee**

### CODE REVIEW

**Comment by dsnet** [comment]
I apologize, but we can't accept this change. See https://github.com/google/go-cmp/pull/225#issuecomment-650431592

**Comment by googollee** [comment]
I understand that it needs to support Go 1.8. As go mod has version control, could we raise the version number to drop the dependency? If users want to use it under Go 1.14, they could pin the version 0.5.x.

**Comment by dsnet** [comment]
See https://github.com/google/go-cmp/pull/225#issuecomment-650434186

**Comment by googollee** [comment]
Thanks for clarifying.

**Pull request closed without merging**
